### ISSUE TITLE
Language pt-BR

### ISSUE THREAD

**Issue by MarcioPaulo** [iteratec/bdd-power-tools#2]
Add. pt-BR language on gherkin.tmLanguage.json

`
{
   "name": "keyword.control.gherkin.pt",
   "match": "(Funcionalidade:|Segundo plano:|Cenário:|Esboço do cenário:|Exemplos:)"
}
`

`
{
  "name": "keyword.other.gherkin.pt",
  "match": "(Dado|Quando|Então|E|Mais)"
}
`

**Comment by cmurczek** [comment]
Hi @MarcioPaulo,
please feel free to submit this as a pull request. Since I don't speak the language I wouldn't be able to verify things are working properly.
